server:
  port: 8383

#EUREKA/DISCOVERY-SERVER CONFIGURATION
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
            - Path=/roles/**
        - id: product-service
            uri: lb://product-service
            predicates:
              - Path=/products/**
      
