server:
  port: 8383

#EUREKA/DISCOVERY-SERVER CONFIGURATION
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

#CLOUD GATEWAY CONFIGURATION
spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 60s
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: http://localhost:8181/user-api/v1.0
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<path>.*), /$\{path}
            
  application:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      
