server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 60s
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        # Authorization Server Route
        - id: authorization-server
          uri: http://authorization-server:9191
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
        
        # Review Service Route
        - id: review-service
          uri: http://review-service:8686
          predicates:
            - Path=/reviews/**
          filters:
            - RewritePath=/reviews/(?<path>.*), /$\{path}

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Management Endpoints Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    enabled: true

# Application Information
info:
  app:
    name: gateway-service
  version: 1.0.0
  description: This service acts as a gateway for the microservices application.
