server:
  port: 9494
  servlet:
    context-path: /api/v1.0.0/shipping-service
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shipping_db
    username: postgres
    password: postgres
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        generate_statistics: true
        jdbc:
          time_zone: UTC


application:
  cors:
    origins: http://localhost:4200,http://localhost:8080

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
  cache:
    disabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

logging:
  level:
    org:
      hibernate:
        type: trace
        SQL: debug

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
